name: Bump Version Tag

on:
  push:
    branches:
      - dev

jobs:
  bump-version:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest commit message
        id: commit-message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_message"
          echo "commit_message=$commit_message" >> $GITHUB_ENV

      - name: Determine version bump
        id: bump
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ -z "$latest_tag" ]; then
            new_version="v1.0.0"
          else
            major=$(echo $latest_tag | cut -d. -f1 | sed 's/v//')
            minor=$(echo $latest_tag | cut -d. -f2)
            patch=$(echo $latest_tag | cut -d. -f3)

            if [[ "${{ env.commit_message }}" == *"major"* ]]; then
              major=$((major + 1))
              minor=0
              patch=0
            elif [[ "${{ env.commit_message }}" == *"minor"* ]]; then
              minor=$((minor + 1))
              patch=0
            else
              patch=$((patch + 1))
            fi

            new_version="v$major.$minor.$patch"
          fi

          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "New version: $new_version"

      - name: Create and push tag
        run: |
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}
